### ISSUE TITLE
benchtool panic: duplicate metrics collector registration attempted 

### ISSUE THREAD

**Issue by CharlieTLe** [cortexproject/cortex-tools#23]
The `benchtool` panics at start up after being built.

```sh
$ make benchtool-image
docker build -t cortexproject/benchtool -f cmd/benchtool/Dockerfile .
[+] Building 22.4s (13/13) FINISHED                                                                                                
 => [internal] load build definition from Dockerfile                                                                          2.2s
 => => transferring dockerfile: 409B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                             2.2s
 => => transferring context: 47B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/golang:1.16.15-stretch                                                     0.8s
 => [internal] load metadata for docker.io/library/alpine:3.14                                                                0.8s
 => [internal] load build context                                                                                             2.0s
 => => transferring context: 150.76MB                                                                                         1.9s
 => [stage-1 1/3] FROM docker.io/library/alpine:3.14@sha256:0f2d5c38dd7a4f4f733e688e3a6733cb5ab1ac6e3cb4603a5dd564e5bfb80eed  0.0s
 => CACHED [build 1/4] FROM docker.io/library/golang:1.16.15-stretch@sha256:13d8ba0c6d1556e568e091fcfdbfab12e74eba8229e19982  0.0s
 => [build 2/4] COPY . /build_dir                                                                                             1.2s
 => [build 3/4] WORKDIR /build_dir                                                                                            0.2s
 => [build 4/4] RUN make clean && make benchtool                                                                             15.5s
 => CACHED [stage-1 2/3] RUN        apk add --update --no-cache ca-certificates                                               0.0s
 => [stage-1 3/3] COPY       --from=build /build_dir/cmd/benchtool/benchtool /usr/bin/benchtool                               0.2s 
 => exporting to image                                                                                                        0.2s 
 => => exporting layers                                                                                                       0.1s 
 => => writing image sha256:c9f4a6685e051fd862d3ffe27003dd0ef86d9a98f30bc995609ac5b71392b208                                  0.0s 
 => => naming to docker.io/cortexproject/benchtool                                                                            0.0s 
docker tag cortexproject/benchtool cortexproject/benchtool:main-9481a59b-WIP

$ docker run -it cortexproject/benchtool -h
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000148eb0, 0xc000288ba0, 0x1, 0x1)
        /build_dir/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0xb7
github.com/prometheus/client_golang/prometheus/promauto.Factory.NewCounter(0x15c0b40, 0xc000148eb0, 0x0, 0x0, 0x0, 0x0, 0x134256d, 0x1c, 0x135fa5a, 0x2d, ...)
        /build_dir/vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go:265 +0x12f
github.com/prometheus/client_golang/prometheus/promauto.NewCounter(...)
        /build_dir/vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go:168
github.com/cortexproject/cortex/pkg/util/flagext.init()
        /build_dir/vendor/github.com/cortexproject/cortex/pkg/util/flagext/deprecated.go:13 +0xcb
```

This is happening because `vendor/github.com/cortexproject/cortex/pkg/util/flagext/deprecated.go` and `vendor/github.com/grafana/dskit/flagext/deprecated.go` are both defining the same metric name `deprecated_flags_inuse_total`.

```go
// DeprecatedFlagsUsed is the metric that counts deprecated flags set.
var DeprecatedFlagsUsed = promauto.NewCounter(
	prometheus.CounterOpts{
		Name: "deprecated_flags_inuse_total",
		Help: "The number of deprecated flags currently set.",
	})
```

Go Dependency Versions:
- github.com/cortexproject/cortex v1.13.2
- github.com/grafana/dskit v0.0.0-20211021180445-3bd016e9d7f1

This also affects the `blockscopy` and `e2ealerting` programs since they both import `dskit`.

**Comment by CharlieTLe** [comment]
Importing `github.com/cortexproject/cortex/pkg/util/flagext` instead of `github.com/grafana/dskit/flagext` makes the problem go away.
